name: Google Cloud Function Deployment
on:
  push:
    branches:
      - main
jobs:
    Deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 1.22.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Set Env for build CGO_ENABLED=0
        run: go env -w CGO_ENABLED=0
      - name: Install dependencies
        run: go get .
      - name: Build and chmod
        run: |
          go build -o bc
          chmod a+x bc
      - name: GCP Authentication
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Debug GCP credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'Transfer file into GCE'
        run: gcloud compute scp bc mymy:~ --zone us-west1-b
      - name: Rename file on GCE
        run: gcloud compute ssh mymy --zone us-west1-b --command 'sudo mv ~/bc /home/awangga/bc'
  